{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Projects\",\"Measures (2)\",\"Key Measures\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.137.1102.0 (24.10)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Measures (2)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
          "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
          "in",
          "    #\"Removed Columns\""
        ],
        "kind": "m",
        "lineageTag": "1634a675-60b1-4275-8512-162fc4911142"
      }
    ],
    "relationships": [
      {
        "name": "c1d40abd-42c4-41a6-9e0a-336028022da9",
        "fromColumn": "Launched",
        "fromTable": "Projects",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_09ddbf5b-08f3-4682-967e-fff6a5f4bde6"
      },
      {
        "name": "a570dcdd-653a-44b5-adf1-1b63eb69df0f",
        "fromColumn": "Deadline",
        "fromTable": "Projects",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_586c2d1a-a8d4-490c-a736-9dc39be73f0c"
      },
      {
        "name": "cca5f5ff-4df3-9b8a-62aa-f472151d39f2",
        "fromColumn": "Launch Date",
        "fromTable": "Projects",
        "toColumn": "Date",
        "toTable": "Date Table"
      }
    ],
    "sourceQueryCulture": "en-IN",
    "tables": [
      {
        "name": "Projects",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b22031e2-ca60-4026-89fa-c191a965a48e",
            "sourceColumn": "ID",
            "summarizeBy": "none"
          },
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "308886d4-70a0-40d6-92e4-ec750e561eb6",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e9c6a81d-0c46-4fb6-945f-32cad58b0cb5",
            "sourceColumn": "Category",
            "summarizeBy": "none"
          },
          {
            "name": "Subcategory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ac0ddb6d-ea7f-4e58-b0b9-0b447d538b54",
            "sourceColumn": "Subcategory",
            "summarizeBy": "none"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8739bddf-dcd7-4cf4-8737-7a4cc54dfef9",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "Launched",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "44fa7f04-33b5-4a75-a1d4-2193370d2645",
            "sourceColumn": "Launched",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_09ddbf5b-08f3-4682-967e-fff6a5f4bde6"
                },
                "isDefault": true,
                "relationship": "c1d40abd-42c4-41a6-9e0a-336028022da9"
              }
            ]
          },
          {
            "name": "Deadline",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "436816b5-080d-4481-ba75-452e95402616",
            "sourceColumn": "Deadline",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_586c2d1a-a8d4-490c-a736-9dc39be73f0c"
                },
                "isDefault": true,
                "relationship": "a570dcdd-653a-44b5-adf1-1b63eb69df0f"
              }
            ]
          },
          {
            "name": "Goal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "af7ff756-c3d6-4edb-9244-6be09498e3ec",
            "sourceColumn": "Goal",
            "summarizeBy": "sum"
          },
          {
            "name": "Pledged",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7bd21dc7-c891-4e5b-9135-af4abb71c469",
            "sourceColumn": "Pledged",
            "summarizeBy": "sum"
          },
          {
            "name": "Backers",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "06482157-b1de-4dc9-abe4-11eb81b62441",
            "sourceColumn": "Backers",
            "summarizeBy": "sum"
          },
          {
            "name": "State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e5331caf-9eb6-48d8-86e0-468f5a69dcd5",
            "sourceColumn": "State",
            "summarizeBy": "none"
          },
          {
            "name": "Launch Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "b29d333e-02bd-4a37-a3f4-4454f858e335",
            "sourceColumn": "Launch Date",
            "summarizeBy": "none"
          },
          {
            "name": "Duration Days",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "aba72ef5-af99-4fdd-98df-bdbabc571052",
            "sourceColumn": "Duration Days",
            "summarizeBy": "sum"
          },
          {
            "name": "Goal Band",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "7b638acc-1874-45a7-8540-7988846d42ed",
            "sortByColumn": "Goal Band Sort",
            "sourceColumn": "Goal Band",
            "summarizeBy": "none"
          },
          {
            "name": "Goal Band Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b7333e8c-ea9c-40aa-8d0c-5dd08ebfdc55",
            "sourceColumn": "Goal Band Sort",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "6627ab4b-70a4-4fbb-9ef7-955c98259e01",
        "partitions": [
          {
            "name": "Projects",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"D:\\Projects\\power-bi-portfolio\\02-kickstarter-projects\\data\\kickstarter_projects.csv\"),[Delimiter=\",\", Columns=11, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"ID\", type text}, {\"Name\", type text}, {\"Category\", type text}, {\"Subcategory\", type text}, {\"Country\", type text}, {\"Launched\", type datetime}, {\"Deadline\", type date}, {\"Goal\", Int64.Type}, {\"Pledged\", Int64.Type}, {\"Backers\", Int64.Type}, {\"State\", type text}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Changed Type\", \"Launch Date\", each Date.From([Launched])),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Added Custom\",{{\"Launch Date\", type date}}),",
                "    #\"Added Custom1\" = Table.AddColumn(#\"Changed Type1\", \"Duration Days\", each Duration.Days([Deadline] - Date.From([Launched]))),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Added Custom1\",{{\"Duration Days\", Int64.Type}}),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Changed Type2\", \"Goal Band\", each if [Goal] < 1000 then \"Under $1K\" else if [Goal] < 5000 then \"$1K to $5K\" else if [Goal] < 10000 then \"$5K to $10K\" else if [Goal] < 25000 then \"$10K to $25K\" else if [Goal] < 50000 then \"$25K to $50K\" else if [Goal] < 100000 then \"$50K to $100K\" else \"$100K+\"),",
                "    #\"Added Conditional Column1\" = Table.AddColumn(#\"Added Conditional Column\", \"Goal Band Sort\", each if [Goal] < 1000 then 1 else if [Goal] < 5000 then 2 else if [Goal] < 10000 then 3 else if [Goal] < 25000 then 4 else if [Goal] < 50000 then 5 else if [Goal] < 100000 then 6 else 7),",
                "    #\"Changed Type3\" = Table.TransformColumnTypes(#\"Added Conditional Column1\",{{\"Goal Band Sort\", Int64.Type}})",
                "in",
                "    #\"Changed Type3\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_a0ab5cb1-cc64-48c4-b7a0-aa936d0e0040",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "2c829117-2edf-4f91-a922-27aa295d0c4f",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b6db9052-e9bf-48e1-8a99-6cfa12ef0116",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "64808a18-1a85-4112-b567-98d093c559d7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "4ba014a7-0d32-470f-81d1-190ab19a07c8",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "17aa873d-5713-4000-bef6-74db7da7a742",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "49aa9622-e116-4900-808f-c40c98b11df5",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "d8e4179d-8ccb-4736-9674-20611cbf8c93",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "63bb39ec-c485-40af-be9a-8a2476467eb8",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "7d661cdf-2a56-47fe-8a0b-fec891d67bc5",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "45d68635-a175-4cf5-b33e-dc6a63fbb6a9",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "8dafb159-b85f-45c9-b185-12b9b308c714",
                "ordinal": 3
              }
            ],
            "lineageTag": "42f9d90b-3da8-4bfb-a5a7-ed43ef4739f2"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "5c91ffcb-40c9-4f82-822a-d2f1418971d3",
        "partitions": [
          {
            "name": "DateTableTemplate_a0ab5cb1-cc64-48c4-b7a0-aa936d0e0040",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_09ddbf5b-08f3-4682-967e-fff6a5f4bde6",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "e9063d55-09ce-4d4e-a3c6-f3ff2118e1ac",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ff6ab3c2-3050-445f-84d7-e1f76ef6f06c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a87b12bb-da14-4f9b-a1f5-e76359580fd2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "974fb9eb-e155-4343-a1d0-7fd2f521c65d",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f79eb940-70ab-45d7-870d-e7664a1e68b5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "f3f9d6aa-6d92-4ac7-bedb-4f0183a4e303",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "4289e943-4b07-4adb-8597-676129204fd3",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "4d30c8d1-0d2b-405a-bcaf-00e0a07ba9e6",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "9e648156-07b5-48fc-93b1-a560673cf7ea",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "98f919ce-64e9-400c-9a25-fb598a935989",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "d3a2781b-fa4d-41a0-b57f-7953adaccb7b",
                "ordinal": 3
              }
            ],
            "lineageTag": "99233cc8-c8d4-4dc3-8090-91d3f9ee2cd9"
          }
        ],
        "isHidden": true,
        "lineageTag": "a16fc9c1-2185-47d9-a4ab-873bf84e1458",
        "partitions": [
          {
            "name": "LocalDateTable_09ddbf5b-08f3-4682-967e-fff6a5f4bde6",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Projects'[Launched])), 1, 1), Date(Year(MAX('Projects'[Launched])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_586c2d1a-a8d4-490c-a736-9dc39be73f0c",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "7a415ec7-528c-4af5-a51d-40e873909474",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f0a6bf6a-3b2b-4087-9e65-078315e7201d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "6f925944-1232-444f-b7e5-08874fbfb9c5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "8817d8ee-c28c-4b58-b3dc-379162eb536c",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b2091809-0e1d-48b4-bb15-55a1a9d2b914",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "9fcbc2dd-7c4b-49b1-9835-c2fe2426b05e",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "3ccc3d6d-3d4b-4667-83c0-7ce5a10c9247",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "10cce602-2f3b-4bf9-855b-ed51fec89b45",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "9fc6781c-8844-404f-aef4-4e47bd3e3ba8",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "f8b1ac49-b649-4064-b827-9bcb214473e2",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "8deb4fac-c61f-4578-a0b2-373d011828c7",
                "ordinal": 3
              }
            ],
            "lineageTag": "1d2c9f59-f237-4d24-8763-ae28eb8230ea"
          }
        ],
        "isHidden": true,
        "lineageTag": "47eeeff9-6747-40fa-ae46-c3cf93febfed",
        "partitions": [
          {
            "name": "LocalDateTable_586c2d1a-a8d4-490c-a736-9dc39be73f0c",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Projects'[Deadline])), 1, 1), Date(Year(MAX('Projects'[Deadline])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Date Table",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "74d4d97378ea44f8aa9f86e3da8a9ed4"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isKey": true,
            "isNameInferred": true,
            "lineageTag": "f6b6b4bb-08b7-479e-846b-ca4a700dbcfa",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "d32cc9d1-dee3-4382-8743-b4cfbfbf46e6",
            "sourceColumn": "[Year]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "790ee202-b12b-474f-a23d-e87aaef39290",
            "sourceColumn": "[Quarter]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "6176af79-ddc8-4a5e-ad6b-cf920a6af342",
            "sourceColumn": "[Month Number]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "91af56dc-e411-42b0-9888-be59acd2cbd2",
            "sortByColumn": "Month Number",
            "sourceColumn": "[Month]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "d21b7086-d03b-4b82-a617-5574aa6726e0",
            "sourceColumn": "[Month Year]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month Year Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "2be869c3-4a6a-4896-9774-45feb411a797",
            "sourceColumn": "[Month Year Sort]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "dataCategory": "Time",
        "lineageTag": "ef42f5ec-96fc-4192-a488-661608efcbd8",
        "partitions": [
          {
            "name": "Date Table",
            "mode": "import",
            "source": {
              "expression": [
                "ADDCOLUMNS(CALENDAR(DATE(2009,1,1), DATE(2018,12,31)),",
                "\"Year\", YEAR([Date]),",
                "\"Quarter\", \"Q\" & QUARTER([Date]),",
                "\"Month Number\", MONTH([Date]),",
                "\"Month\", FORMAT([Date], \"mmm\"),",
                "\"Month Year\", FORMAT([Date], \"mmm yyyy\"),",
                "\"Month Year Sort\", YEAR([Date])* 100 + MONTH([Date]))"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Key Measures",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "Name"
          }
        ],
        "lineageTag": "01f11c66-afb6-480e-a5b7-16afe33d5c0f",
        "measures": [
          {
            "name": "Total Projects",
            "expression": "COUNTROWS(Projects) ",
            "formatString": "#,0",
            "lineageTag": "2b7db5d5-10e1-4edd-8dea-0a45bef5eea9"
          },
          {
            "name": "Successful Projects",
            "expression": "CALCULATE([Total Projects], Projects[State] = \"Successful\")",
            "formatString": "0",
            "lineageTag": "2a93ec48-f74e-4e16-8e0c-85a83a6bb909"
          },
          {
            "name": "Resolved Projects",
            "expression": "CALCULATE([Total Projects], Projects[State] IN {\"Successful\", \"Failed\"})",
            "formatString": "0",
            "lineageTag": "6013f001-66d5-4fb1-981e-3bff1f6ea666"
          },
          {
            "name": "Success Rate",
            "expression": "DIVIDE([Successful Projects],[Resolved Projects])",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "9f8f4a54-2ea8-4dc4-b39d-bd40540f3fce"
          },
          {
            "name": "Total Pledged",
            "expression": "SUM(Projects[Pledged])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "1d7b8945-64d8-46ee-81c0-22f4e28f9528"
          },
          {
            "name": "Total Backings",
            "expression": "SUM(Projects[Backers])",
            "formatString": "#,0",
            "lineageTag": "2ab01c4c-1e5f-48b2-8cb4-b6a9bed9a12c"
          },
          {
            "name": "Median Goal",
            "expression": "MEDIAN(Projects[Goal])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "c46f57f6-7e9b-400a-9ff1-b1cc89cb2145"
          },
          {
            "name": "Median Pledged",
            "expression": "MEDIAN(Projects[Pledged])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "a72eec37-0f5a-4740-a4dc-71322d0fa8f4"
          },
          {
            "name": "Avg Pledge per Backer",
            "expression": "DIVIDE([Total Pledged], [Total Backings])",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "d4f4fd70-5b54-4b98-910c-c8658fcf7bb8"
          },
          {
            "name": "Backings per Project",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "DIVIDE([Total Backings], [Total Projects])",
            "lineageTag": "4edba1ba-2e94-45cd-be94-3ef758dbdc20"
          },
          {
            "name": "Median Pct of Goal",
            "expression": [
              "",
              "MEDIANX(Projects, DIVIDE(Projects[Pledged], Projects[Goal]))"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "86fd2f23-4f35-40de-9c7b-2408253f5dc0"
          }
        ],
        "partitions": [
          {
            "name": "Key Measures",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}