{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"athlete_events\",\"Country\",\"Athlete\",\"Games\",\"Event\",\"Entries\",\"_Measures\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.137.1102.0 (24.10)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "athlete_events",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Csv.Document(File.Contents(\"D:\\Projects\\power-bi-portfolio\\03-olympic-athletes\\data\\athlete_events.csv\"),[Delimiter=\",\", Columns=15, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
          "    #\"Replaced Value\" = Table.ReplaceValue(#\"Promoted Headers\",\"NA\",null,Replacer.ReplaceValue,{\"Age\", \"Height\", \"Weight\"}),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Replaced Value\",{{\"ID\", Int64.Type}, {\"Name\", type text}, {\"Sex\", type text}, {\"Age\", Int64.Type}, {\"Height\", type number}, {\"Weight\", type number}, {\"Team\", type text}, {\"NOC\", type text}, {\"Games\", type text}, {\"Year\", Int64.Type}, {\"Season\", type text}, {\"City\", type text}, {\"Sport\", type text}, {\"Event\", type text}, {\"Medal\", type text}}),",
          "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Changed Type\",\"NA\",null,Replacer.ReplaceValue,{\"Medal\"})",
          "in",
          "    #\"Replaced Value1\""
        ],
        "kind": "m",
        "lineageTag": "fed7134c-fb1f-4856-ab15-2a649f20d05f"
      }
    ],
    "relationships": [
      {
        "name": "AutoDetected_b6d0a4a7-4812-4ca9-b4ea-a991b77e3204",
        "fromColumn": "NOC",
        "fromTable": "Entries",
        "toColumn": "NOC",
        "toTable": "Country"
      },
      {
        "name": "AutoDetected_60435a3e-df6b-468f-8990-d3fb91120026",
        "fromColumn": "Games",
        "fromTable": "Entries",
        "toColumn": "Games",
        "toTable": "Games"
      },
      {
        "name": "AutoDetected_000918f5-3bfb-4a2a-b4a7-9de19731f656",
        "fromColumn": "Event",
        "fromTable": "Entries",
        "toColumn": "Event",
        "toTable": "Event"
      },
      {
        "name": "779d62d7-1e95-0820-4b0b-c9c472e39a20",
        "fromColumn": "ID",
        "fromTable": "Entries",
        "toColumn": "ID",
        "toTable": "Athlete"
      }
    ],
    "sourceQueryCulture": "en-IN",
    "tables": [
      {
        "name": "Country",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "Name"
          }
        ],
        "columns": [
          {
            "name": "NOC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "65cc38e5-3626-4691-8a37-213117a9778c",
            "sourceColumn": "NOC",
            "summarizeBy": "none"
          },
          {
            "name": "region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8ff7ff3e-9957-4c49-a04d-d29c1039cd27",
            "sourceColumn": "region",
            "summarizeBy": "none"
          },
          {
            "name": "notes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8527c87b-fe63-4ed3-a4ff-9d70b27043b6",
            "sourceColumn": "notes",
            "summarizeBy": "none"
          },
          {
            "name": "country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "170fcae1-ec24-4a93-b85a-8bc431e1f054",
            "sourceColumn": "country",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "cc600d92-8e5f-4da1-b723-3ba2418e3946",
        "partitions": [
          {
            "name": "Country",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"D:\\Projects\\power-bi-portfolio\\03-olympic-athletes\\data\\country_definitions.csv\"),[Delimiter=\",\", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"NOC\", type text}, {\"region\", type text}, {\"notes\", type text}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Changed Type\",\"NA\",null,Replacer.ReplaceValue,{\"region\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"SIN\",\"SGP\",Replacer.ReplaceText,{\"NOC\"}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Replaced Value1\", \"country\", each if [region] = null then [notes] else [region]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Added Custom\",{{\"country\", type text}}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Changed Type1\", each true)",
                "in",
                "    #\"Filtered Rows\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Athlete",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "092d42d3-ec6e-40f6-a733-a88c4c41dcc5",
            "sourceColumn": "ID",
            "summarizeBy": "none"
          },
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "782d20d6-dd65-402a-9bb7-8ad0f7243afe",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "Sex",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a43ecfa5-5da2-43f2-b57a-b993eaa4fde9",
            "sourceColumn": "Sex",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "fc07f859-79c3-4cb4-8804-829f1ba7297f",
        "partitions": [
          {
            "name": "Athlete",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = athlete_events,",
                "    #\"Removed Other Columns\" = Table.SelectColumns(Source,{\"ID\", \"Name\", \"Sex\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Other Columns\")",
                "in",
                "    #\"Removed Duplicates\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Games",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Games",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2098dbc2-b0d4-45ae-b005-968818717aa0",
            "sourceColumn": "Games",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8182152b-cfc6-4459-896c-b68b14910e54",
            "sourceColumn": "Year",
            "summarizeBy": "none"
          },
          {
            "name": "Season",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f60b6c4b-c021-4e57-b394-ac628c3f1a7b",
            "sourceColumn": "Season",
            "summarizeBy": "none"
          },
          {
            "name": "City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1cbfd07f-7bd6-424d-b694-04a0d1e5224f",
            "sourceColumn": "City",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "047ff9f1-a4fc-421e-96ee-00adb5017494",
        "partitions": [
          {
            "name": "Games",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = athlete_events,",
                "    #\"Removed Other Columns\" = Table.SelectColumns(Source,{\"Games\", \"Year\", \"Season\", \"City\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Other Columns\", {\"Games\"})",
                "in",
                "    #\"Removed Duplicates\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Event",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Sport",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c37851de-1954-4097-8dd3-17474fb27a92",
            "sourceColumn": "Sport",
            "summarizeBy": "none"
          },
          {
            "name": "Event",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1ac8048f-c00c-49f1-9c05-7a87ee9ff0b6",
            "sourceColumn": "Event",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "b98e5e54-49bb-4929-9a4f-d52e6198c0bb",
        "partitions": [
          {
            "name": "Event",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = athlete_events,",
                "    #\"Removed Other Columns\" = Table.SelectColumns(Source,{\"Sport\", \"Event\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Other Columns\")",
                "in",
                "    #\"Removed Duplicates\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Entries",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e2c335c6-50a3-4bc9-b0c7-21332829d031",
            "sourceColumn": "ID",
            "summarizeBy": "none"
          },
          {
            "name": "Age",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ec260152-103f-46b9-8e43-683b84adc86f",
            "sourceColumn": "Age",
            "summarizeBy": "sum"
          },
          {
            "name": "Height",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d6503ecf-6abb-44d2-9612-22a4d3a1dd7e",
            "sourceColumn": "Height",
            "summarizeBy": "sum"
          },
          {
            "name": "Weight",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8b40ea2e-bb99-4aa7-8980-27832dcf6ec7",
            "sourceColumn": "Weight",
            "summarizeBy": "sum"
          },
          {
            "name": "NOC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "910f41eb-4a5e-4351-bbca-4cc98dc03622",
            "sourceColumn": "NOC",
            "summarizeBy": "none"
          },
          {
            "name": "Games",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "c49c5890-6708-47dd-840a-65376304cab1",
            "sourceColumn": "Games",
            "summarizeBy": "none"
          },
          {
            "name": "Event",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "c90ed090-1a7c-418f-9896-7ca1b8aca1c5",
            "sourceColumn": "Event",
            "summarizeBy": "none"
          },
          {
            "name": "Medal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5401ced2-62f1-40f4-80bc-3ae33f503284",
            "sourceColumn": "Medal",
            "summarizeBy": "none"
          },
          {
            "name": "MedalKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "abfdd540-1345-42dd-847f-8fd6cceeed6d",
            "sourceColumn": "MedalKey",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "182f7225-cd4c-4c3e-a0a2-193ad2ac9782",
        "partitions": [
          {
            "name": "Entries",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = athlete_events,",
                "    #\"Removed Columns\" = Table.RemoveColumns(Source,{\"Name\", \"Sex\", \"Team\", \"Year\", \"Season\", \"City\", \"Sport\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Columns\"),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Removed Duplicates\", \"MedalKey\", each if [Medal] = null then null",
                "else [Games] & \"|\" & [Event] & \"|\" & [Medal] & \"|\" & [NOC]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Added Custom\",{{\"MedalKey\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "_Measures",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "b33c32be-b890-4ac6-ad11-3dd360473c67",
        "measures": [
          {
            "name": "Entries",
            "expression": "COUNTROWS(Entries)",
            "formatString": "#,0",
            "lineageTag": "1981c30c-ba76-48a8-9121-21ba0a721386"
          },
          {
            "name": "Athletes",
            "expression": "DISTINCTCOUNT(Entries[ID])",
            "formatString": "#,0",
            "lineageTag": "814e453b-daea-4843-a533-67d24cde4de7"
          },
          {
            "name": "Medal Rows",
            "expression": "CALCULATE(COUNTROWS(Entries), NOT ISBLANK(Entries[Medal]))",
            "formatString": "#,0",
            "lineageTag": "b0f34594-4a29-4f93-b134-a99e4391e4f8"
          },
          {
            "name": "Medals",
            "expression": "DISTINCTCOUNTNOBLANK(Entries[MedalKey])",
            "formatString": "#,0",
            "lineageTag": "522f179a-d633-4a3e-b8b2-d366b0c8bc60"
          },
          {
            "name": "Countries",
            "expression": "DISTINCTCOUNT(Entries[NOC])",
            "formatString": "#,0",
            "lineageTag": "28124027-1831-4dee-b8fd-a065f6a7059e"
          },
          {
            "name": "Sports",
            "expression": "COUNTROWS(SUMMARIZE(Entries, Event[Sport]))",
            "formatString": "#,0",
            "lineageTag": "3f700ee9-ca6b-4272-a5d5-ab8292a20abe"
          },
          {
            "name": "Events Contested",
            "expression": "DISTINCTCOUNT(Entries[Event])",
            "formatString": "#,0",
            "lineageTag": "cc7d7f9e-8b5d-4abc-a388-dcd0b98a2c08"
          },
          {
            "name": "Gold",
            "expression": "CALCULATE([Medals], Entries[Medal] = \"Gold\")",
            "formatString": "#,0",
            "lineageTag": "9a746385-a101-4308-b76f-17444c717b7b"
          },
          {
            "name": "Silver",
            "expression": "CALCULATE([Medals], Entries[Medal] = \"Silver\")",
            "formatString": "#,0",
            "lineageTag": "377bba57-4f36-4be3-a237-95a633ef84b9"
          },
          {
            "name": "Bronze",
            "expression": "CALCULATE([Medals], Entries[Medal] = \"Bronze\")",
            "formatString": "#,0",
            "lineageTag": "70cf660a-02f4-43b8-8477-40740fc9ebc8"
          },
          {
            "name": "Medals per 100 Athletes",
            "expression": "DIVIDE([Medals], [Athletes]) * 100",
            "formatString": "0.0",
            "lineageTag": "3eabf551-66bc-48da-a7ce-926d3c79549d"
          },
          {
            "name": "Female Athletes",
            "expression": "CALCULATE([Athletes], Athlete[Sex] = \"F\")",
            "formatString": "#,0",
            "lineageTag": "f1cc2112-97be-4293-adfa-64b6b4005254"
          },
          {
            "name": "Female Share",
            "expression": "DIVIDE([Female Athletes], [Athletes])",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "5477c936-2ba4-4c02-bacf-22ca122c4cea"
          },
          {
            "name": "Median Age",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "MEDIAN(Entries[Age])",
            "lineageTag": "4612bbd8-3652-4be9-a893-70f2fd2e4997"
          },
          {
            "name": "Avg Height cm",
            "expression": "AVERAGE(Entries[Height])",
            "formatString": "0.0",
            "lineageTag": "3a0bfa03-2b15-4b65-a74e-b9f799f36841"
          },
          {
            "name": "Avg Weight kg",
            "expression": "AVERAGE(Entries[Weight])",
            "formatString": "0.0",
            "lineageTag": "22b8f203-9a63-49e4-a953-59ec6e5e5ab0"
          }
        ],
        "partitions": [
          {
            "name": "_Measures",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}